### ISSUE TITLE
lasso behind histogram 

### ISSUE THREAD

**Issue by ravenep** [ofgulban/segmentator#84]
Hello, 

I've had trouble with the selection roi always being presented behind the histogram so you can't really see where it is. Have tried on two systems and same issue, 

CentOS 7
MacOS 10.12.6

Is this a setting I've missed? Or do you have any recommendations to fix this? 

<img width="549" alt="Screen Shot 2019-06-13 at 5 28 57 PM" src="https://user-images.githubusercontent.com/12449573/59450314-da973e80-8e00-11e9-9465-d56d6214144f.png">

Thank you!
Erika

**Comment by ofgulban** [comment]
Hi Erika,

Thanks a lot for reporting this issue. 

Could you post which version of matplotlib are you using? It would help me to replicate and fix this issue.

Faruk

**Comment by ofgulban** [comment]
@MSchnei , if you have time could you check whether we can replicate this glitch? I will be traveling until monday.

**Comment by ravenep** [comment]
Sure thing, for linux, matplotlib==3.1.0 and mac, matplotlib==3.0.3

Thanks!

**Comment by ofgulban** [comment]
Thanks, this is same as #80 then. It is glitch that came with matplotlib version 3. I didnt have time to investigate it properly yet.

As a solution, I recommend you to install segmentator in a virtual python environment. If you have a look at [requirements.txt](https://github.com/ofgulban/segmentator/blob/master/requirements.txt) you will see that we have fixed matplotlib version to 2.0.2. Once you have created a virtual environment you can follow the steps written in [here](https://github.com/ofgulban/segmentator/wiki/Installation) to have the tested dependencies installed.

Try the suggestion above and let me know if you have issues.

**Comment by ravenep** [comment]
Thanks for getting back. I tried using a virtual environment, but am still having the same issue. It was unhappy with using an older scipy (and numpy which seems to be a dependency), but I was able to get the recommended versions on compoda, matplotlib, and nibabel. 

Packages inside virtual env, 

compoda==0.3.3
cycler==0.10.0
matplotlib==2.0.2
nibabel==2.1.0
numpy==1.16.4
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2019.1
scipy==1.3.0
six==1.12.0

-e

**Comment by ingo-m** [comment]
Just to make sure that this is not (another) mac OS specific issue: I cannot reproduce the issue on mac OS 10.14.5, with Segmentator 1.5.2, and Python 3.6.7, given the following dependencies (selection):

```
compoda                   0.3.3                    pypi_0    pypi
matplotlib                2.2.2                    pypi_0    pypi
nibabel                   2.2.1                    pypi_0    pypi
numpy                     1.14.2                   pypi_0    pypi
python                    3.6.7                haf84260_0  
scipy                     1.0.0                    pypi_0    pypi
setuptools                40.6.2                   py36_0  
```
<img width="1106" alt="segmentator" src="https://user-images.githubusercontent.com/10960892/59553580-ff251f00-8f96-11e9-93f7-dd7d3df06741.png">

**Comment by ingo-m** [comment]
It turns out that segmentator's requirements cannot be installed in python 3.7 (numpy installation fails). This is not a big surprise, because segmentator is currently only tested under Python 3.6 & Python 2.7. I suggest you do the following:

```bash
# Create a new conda environment for segmentator, specifying the python version to be 3.6:
conda create --name segmentator python=3.6 pip

# Download segmentator release from github:
# https://github.com/ofgulban/segmentator/releases/tag/v1.5.3

# Unzip the downloaded file.

# Go into the new directory (you may want to move the directory somewhere eles first):
cd /Users/john/Downloads/segmentator-1.5.3

# Install requirements:
pip install -r requirements.txt

# Install segmentator:
python setup.py install
```

I just tested this (again on mac OS 10.14.5), and the issue does not occur.

<img width="1102" alt="Screenshot 2019-06-15 at 18 17 24" src="https://user-images.githubusercontent.com/10960892/59553809-f33b5c00-8f9a-11e9-9161-3fbd0a1efedc.png">

**Comment by ravenep** [comment]
that worked! thanks for your help! 

-e

**Comment by ofgulban** [comment]
@ravenep & @ingo-m , thanks a lot for solving this issue when I was away 🎉 . I will still investigate this. Probably i should make use of ‘zorder’ flag while updating plots to prevent this glitch. 

@ingo-m maybe we should incorporate your installation suggestions to the wiki installation page.
